# Generated by Django 5.0.14 on 2026-06-13 06:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_score', models.IntegerField(help_text='Mood score from 1 (very low) to 5 (excellent)')),
                ('stress_score', models.IntegerField(help_text='Stress score from 1 (no stress) to 5 (extreme stress)')),
                ('energy_level', models.IntegerField(help_text='Energy level from 1 (very low) to 5 (very high)')),
                ('sleep_quality', models.IntegerField(help_text='Sleep quality from 1 (terrible) to 5 (excellent)')),
                ('study_satisfaction', models.IntegerField(help_text='Study satisfaction from 1 (unsatisfied) to 5 (highly satisfied)')),
                ('logged_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_date'],
                'unique_together': {('user', 'logged_date')},
            },
        ),
    ]
