# Generated by Django 5.0.14 on 2026-06-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodlog',
            name='energy_level',
            field=models.IntegerField(choices=[(1, 'Exhausted / Low'), (2, 'Tired / Sluggish'), (3, 'Normal / Steady'), (4, 'High Energy'), (5, 'Peaked / Very Active')], help_text='Energy level from 1 (very low) to 5 (very high)'),
        ),
        migrations.AlterField(
            model_name='moodlog',
            name='mood_score',
            field=models.IntegerField(choices=[(1, 'Very Low / Depressed'), (2, 'Low / Anxious'), (3, 'Neutral / Okay'), (4, 'Good / Happy'), (5, 'Excellent / Energetic')], help_text='Mood score from 1 (very low) to 5 (excellent)'),
        ),
        migrations.AlterField(
            model_name='moodlog',
            name='sleep_quality',
            field=models.IntegerField(choices=[(1, 'Terrible / Restless'), (2, 'Poor Sleep'), (3, 'Average / Sufficient'), (4, 'Good Rest'), (5, 'Deep / Restorative')], help_text='Sleep quality from 1 (terrible) to 5 (excellent)'),
        ),
        migrations.AlterField(
            model_name='moodlog',
            name='stress_score',
            field=models.IntegerField(choices=[(1, 'No Stress / Calm'), (2, 'Low Stress'), (3, 'Moderate / Manageable'), (4, 'High Stress / Heavy'), (5, 'Extreme Stress / Overwhelmed')], help_text='Stress score from 1 (no stress) to 5 (extreme stress)'),
        ),
        migrations.AlterField(
            model_name='moodlog',
            name='study_satisfaction',
            field=models.IntegerField(choices=[(1, 'Highly Unsatisfied'), (2, 'Disappointed'), (3, 'Acceptable / Progressing'), (4, 'Satisfied / Productive'), (5, 'Highly Satisfied / Peak Study Day')], help_text='Study satisfaction from 1 (unsatisfied) to 5 (highly satisfied)'),
        ),
    ]
