# Generated by Django 5.0.14 on 2026-06-13 07:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0002_alter_moodlog_energy_level_alter_moodlog_mood_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthDataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_date', models.DateField(default=django.utils.timezone.now)),
                ('steps', models.IntegerField(default=0, help_text='Daily steps synced from device')),
                ('sleep_hours', models.FloatField(default=0.0, help_text='Daily sleep duration in hours')),
                ('resting_heart_rate', models.IntegerField(default=70, help_text='Average resting heart rate')),
                ('source', models.CharField(default='Apple Health', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_date'],
                'unique_together': {('user', 'logged_date')},
            },
        ),
    ]
