# Generated by Django 5.0.14 on 2026-06-13 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0003_healthdatalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdatalog',
            name='active_minutes',
            field=models.IntegerField(default=0, help_text='Daily active minutes'),
        ),
        migrations.AddField(
            model_name='healthdatalog',
            name='avg_heart_rate',
            field=models.IntegerField(default=0, help_text='Average daily heart rate'),
        ),
        migrations.AddField(
            model_name='healthdatalog',
            name='bmi',
            field=models.FloatField(default=0.0, help_text='User Body Mass Index'),
        ),
        migrations.AddField(
            model_name='healthdatalog',
            name='calories_burned',
            field=models.IntegerField(default=0, help_text='Daily calories burned'),
        ),
        migrations.AddField(
            model_name='healthdatalog',
            name='exercise_duration_minutes',
            field=models.IntegerField(default=0, help_text='Total exercise duration in minutes'),
        ),
        migrations.AddField(
            model_name='healthdatalog',
            name='exercise_sessions_count',
            field=models.IntegerField(default=0, help_text='Count of exercise/workout sessions'),
        ),
        migrations.AddField(
            model_name='healthdatalog',
            name='max_heart_rate',
            field=models.IntegerField(default=0, help_text='Maximum daily heart rate'),
        ),
        migrations.AddField(
            model_name='healthdatalog',
            name='mindfulness_minutes',
            field=models.IntegerField(default=0, help_text='Daily mindfulness/meditation minutes'),
        ),
        migrations.AddField(
            model_name='healthdatalog',
            name='sleep_quality_score',
            field=models.IntegerField(default=0, help_text='Sleep quality score from 1 to 100'),
        ),
        migrations.AddField(
            model_name='healthdatalog',
            name='stress_level_score',
            field=models.IntegerField(default=0, help_text='Stress score from 1 to 100'),
        ),
        migrations.AddField(
            model_name='healthdatalog',
            name='weight_kg',
            field=models.FloatField(default=0.0, help_text='User weight in kg'),
        ),
        migrations.CreateModel(
            name='HealthIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('google_fit', 'Google Fit'), ('apple_health', 'Apple Health'), ('fitbit', 'Fitbit'), ('smart_band', 'Smartwatch/Fitness Band')], max_length=50)),
                ('is_connected', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('allow_steps', models.BooleanField(default=True)),
                ('allow_heart_rate', models.BooleanField(default=True)),
                ('allow_sleep', models.BooleanField(default=True)),
                ('allow_calories', models.BooleanField(default=True)),
                ('allow_exercise', models.BooleanField(default=True)),
                ('allow_weight_bmi', models.BooleanField(default=True)),
                ('allow_stress', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'platform')},
            },
        ),
    ]
