# Generated by Django 5.0.14 on 2026-06-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0004_healthdatalog_active_minutes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodlog',
            options={'ordering': ['-logged_date', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='moodlog',
            unique_together=set(),
        ),
    ]
